### ISSUE TITLE
Colored chest vs ender backpack

### ISSUE THREAD

**Issue by trip28** [TheBusyBiscuit/ColoredEnderChests#14]
Hi, could you add a feature that would prevent the connection of colored ender chest with ender backpack?
To keep the ender backpack connected only to the vanilla enderchest. Or the ability to set colors directly on the ender backpack for connect with colored ender chest.

**Comment by TheBusyBiscuit** [comment]
This is a bug tracker, if you have a question or suggestion, then please post it on the Slimefun discord server (once discord is working again...)

**Comment by trip28** [comment]
I thought you would react like this ... but it's a problem / error ... when I use ender back pack and colored enderchest + extraction node from Fluffy machines addon I can't use tier II talisman. (which must be in the ender backpack for it to work) there is no way to separate the ender chest and backpack
