### ISSUE TITLE
Enderchests are shared between all players.

### ISSUE THREAD

**Issue by mrcoffee1026** [TheBusyBiscuit/ColoredEnderChests#6]
Fairly confident these are not supposed to work this way but feel free to enlighten me if I've missed the point.  We had believed that the color tops were also specific to player... so if I make one colored white+white+white... and another player made that exact color combination... we could still have inventories in these chests that were not the same.  Instead... all matching colors are linked whether or not the player has made and used one of that color previously. We have found that we are effectively sharing the same inventory and items among the chests.  Is that how this was supposed to work?  (in such a way that a player needs only see your chest in order to have all the information they need to remove all of the items from it).

**Comment by TheBusyBiscuit** [comment]
It is supposed to work that way.
Otherwise it wouldn't work with Cargo Networks too.

**Comment by mrcoffee1026** [comment]
alright.  I guess we might find that useful if chest terminal wasn't a thing, but since it is I don't think anyone had the idea they were publicly sharing inventories of these chests.  Thanks for clearing up the confusion.
