### ISSUE TITLE
Server Lag with plugin enabled on latest 1.14.4 paper spigot

### ISSUE THREAD

**Issue by cybermancerr** [TheBusyBiscuit/ColoredEnderChests#8]
## Description (Required)

having lag issues with ColoredEnderChests.  I have tried ColoredEnderChests - DEV 7 (git 6885c).jar and lower with the same lag issues when players trying to break blocks and killing mobs.  My spigot 1.14.4 server was unplayable.  To isolate the plugin I had to disable all server plugins and enable them one at a time until the issues came back.  Took me all weekend to isolate it to this addon.  All other Slimefun plugins work great.  I have told my players I will keep ColoredEnderChests disabled until I can figure out a possible solution.  To note the players reported that they placed shulker boxes with items into their colored ender chests, which is the only thing I can think can cause possible issues.  The console does not throw any errors. 
## Steps to reproduce the Issue (Required)

Tried to dig or mine blocks as normal with 2 players online.  When one player starts digging the other player starts getting rubber banding effect when mining or killing mobs.  With McMMO Giga breaker activated all players are not able to move or break any more blocks until server catches up.

## Expected behavior (Required)
Expected no lag issues with killing mobs or breaking blocks.

## Server Log / Error Report

Server log without ColoredEnderChests disabled: https://pastebin.com/0dYVuGD0
Timings without plugin enabled: https://timings.aikar.co/?id=8e81ca33f1174702a527c757d6a9fcee

Server log with ColoredEnderChests enabled: https://pastebin.com/AS5xYeks
Timings with plugin enabled: https://timings.aikar.co/?id=604cc796438e4baa8c1ece2879e998d8

## Environment (Required)

 - Minecraft Version: This server is running Paper version git-Paper-230 (MC: 1.14.4) (Implementing API version 1.14.4-R0.1-SNAPSHOT)
 - Slimefun Version: Slimefun vRC - 3 (git 8a605404)
 - CS-CoreLib Version: CS-CoreLib vDEV - 78 (git 199e1b1e)
 - ColoredEnderChests Version: ColoredEnderChests vDEV - 7 (git 6885cb88)

**Comment by EnderBro123** [comment]
I don't think this'll get fixed since your using a Stable build. Switch to the latest Dev build.

**Comment by cybermancerr** [comment]
Just tried it with Slimefun vDEV - 343 (git 61a58d87) and same problem.

Here is the log and timings with ColorEnderChests enabled.
https://pastebin.com/uunmFb9W
https://timings.aikar.co/?id=574e300534594e44ae824b1b8c5aa663

**Comment by J3fftw1** [comment]
Its not a issue that is related to the main plugin so it will get fixed

**Comment by cybermancerr** [comment]
colored ender chests are still broken in regards to lag look at this https://timings.aikar.co/?id=3e3b81a86f854587ae7e242b9b42afbe#timings

i removed it and everything back to normal
I updated to today's build of SF and still the same.
looks like the right click event on self is causing the most lag
i used crackshot plugin to simulate fast right click action by just holding right click on the mouse down.

**Comment by TheBusyBiscuit** [comment]
Can you try again with Slimefun build 484 and the latest build of ColoredEnderChests?
Would be awesome if you could send a timings report again for comparison.
